---
- name: Testing Kafka
  hosts: localhost

  sources:
    - name: Kafka
      ansible.eda.kafka:
        host: ryzen5.lab.automate.nyc
        port: 9094
        topic: syslog-queue

  rules:
    - name: When message is hello
      condition: event.body.message == 'hello'
      actions:
        - print_event:
            pretty: true

    - name: Watson Alert - outofmemory
      condition:
        all:
          - event.body.watsonAlert.canonicalAlert.identity.summary is search('outofmemory')
#          - event.body.watsonAlert.canonicalAlert.identity.summary is defined
      actions:
        - print_event:
            pretty: true
  
